apiVersion: apps/v1
kind: Deployment
metadata:
  name: surveypython-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: surveypython-app
  template:
    metadata:
      labels:
        app: surveypython-app
    spec:
      containers:
      - name: surveypython-app
        image: gcr.io/group-python/surveypython-app:cleanlatest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_USER
          value: "admin"
        - name: DB_PASS
          value: "surveypass"
        - name: DB_NAME
          value: "surveypythondb"
        - name: DB_HOST
          value: "surveypythondb.c9wc8aya24by.us-east-1.rds.amazonaws.com"
        - name: DB_PORT
          value: "3306"
      imagePullSecrets:
      - name: gcr-json-key