apiVersion: v1
kind: Service
metadata:
  name: surveypython-service
spec:
  type: LoadBalancer
  selector:
    app: surveypython-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
